export const REQUIRED_COLLECTIONS = [
  'users',
  'universities',
  'institutes',
  'students',
  'documents',
  'enrollments',
  'insurance',
  'payments',
  'reviews',
  'ecards',
  'uploads',
  'auditLogs',
  'notifications',
  'settings',
  'refreshTokens',
  'migrationIdMaps',
  'migrationRuns',
  'migrationIssues',
  'knowledgeDocuments',
  'knowledgeChunks',
  'aiConversations',
  'aiFeedback',
  'aiUsage',
  'announcements',
  'notificationTemplates',
  'emailLogs',
  'jobRuns',
  'dataSubmissions',
  'premiumRules',
  'premiumCalculations',
  'submissionVersions'
] as const;

export type CollectionName = (typeof REQUIRED_COLLECTIONS)[number];
